### ISSUE TITLE
java.lang.IllegalArgumentException: URI is not absolute

### ISSUE THREAD

**Issue by AleksMeshkov** [RaananW/PhoneGap-Image-Resizer#11]
Hi! My android app got crashed after attempt to resize an image.

```
imageResizer.resizeImage(ok,err, "file:///data/data/com.mtw.sarafan/files/resized", 40, 40, {pixelDensity: false, storeImage: true})
```

I get:

```
FATAL EXCEPTION: pool-1-thread-6
E/AndroidRuntime(12929): java.lang.IllegalArgumentException: URI is not absolute:
E/AndroidRuntime(12929):    at java.io.File.checkURI(File.java:220)
E/AndroidRuntime(12929):    at java.io.File.<init>(File.java:177)
E/AndroidRuntime(12929):    at com.synconset.ImageResizePlugin$ImageTools.storeImage(ImageResizePlugin.java:113)
E/AndroidRuntime(12929):    at com.synconset.ImageResizePlugin$ResizeImage.run(ImageResizePlugin.java:214)
E/AndroidRuntime(12929):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(12929):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(12929):    at java.lang.Thread.run(Thread.java:841)
```

Could you please help with this issue? Thanks in advance!

**Comment by Bessonov** [comment]
Had same error. set `directory` and `filename` helped me.
